routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();
// Dashboard
Route::get('/', 'HomeController@index')->name('home');
// My Profile
Route::get('/profile/{user}', 'HomeController@myProfile')->name('profile');
Route::get('/profile/edit/{user}', 'HomeController@edit')->name('profile.edit');
Route::post('/profile/follow/{user}', 'HomeController@follow')->name('profile.follow');
Route::patch('/profile/update/{user}', 'HomeController@update')->name('profile.update');
// Posts
Route::get('/posts', 'PostController@index')->name('posts');
Route::get('/posts/create', 'PostController@create')->name('posts.create');
Route::get('/posts/edit/{post}', 'PostController@edit')->name('posts.edit');
Route::get('/posts/show/{post}', 'PostController@show')->name('posts.show');
Route::patch('/posts/edit/{post}', 'PostController@update')->name('posts.update');
Route::post('/posts', 'PostController@store')->name('posts.store');
Route::delete('/posts/delete/{post}', 'PostController@destroy')->name('posts.delete');
// Like
Route::post('/posts/like/{post}', 'PostController@like')->name('posts.like');
// Comment
Route::post('/comments/{post}', 'CommentController@store')->name('comments.store');
Route::delete('/comments/delete/{comment}', 'CommentController@destroy')->name('comments.delete');
Route::post('/comments/like/{comment}', 'CommentController@like')->name('comments.like');

// File Manager Test (WYSIWYG)
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
  \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model {
  protected $guarded = [
    "id", "created_at", "updated_at",
  ];
  function user() {
    return $this->belongsTo(User::class);
  }
  function comments() {
    return $this->hasMany(Comment::class);
  }
  function likes() {
    return $this->hasMany(PostLike::class);
  }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\PostLike;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller {
  public function __construct() {
    $this->middleware('auth');
  }
  public function index() {
    $userId = Auth::user()->id;
    $posts = Post::with('user', 'likes')
      ->withCount('likes', 'comments')
      ->where('user_id', '=', $userId)
      ->orderBy('id', 'DESC')
      ->get();
    return view('posts.index', ['posts' => $posts]);
  }
  public function create() {
    return view('posts.create');
  }

  public function store(Request $request) {
    $request->validate([
      'title' => 'required|string',
      'content' => 'required|string',
      'image' => 'mimes:jpeg,png,jpg,gif,svg',
      'image.*' => 'mimes:jpeg,png,jpg,gif,svg',
    ]);
    $userId = Auth::user()->id;
    $datas = $request->all();
    $datas['user_id'] = $userId;
    if ($files = $request->file('image')) {
      // Define upload path
      $destinationPath = public_path('/images/'); // upload path
      // Upload Orginal Image
      $profileImage = date('YmdHis') . "." . $files->getClientOriginalExtension();
      $files->move($destinationPath, $profileImage);
      $datas['url_image'] = "$profileImage";
    }
    Post::create($datas);
    toast('Post Has Been Submitted !', 'success');
    return redirect('/');
  }

  public function show(Post $post) {
    $myPost = $post
      ->with(['comments' => function ($query) {
        $query->with('likes')->withCount('likes');
      }])
      ->with('user', 'likes')
      ->withCount('likes', 'comments')
      ->where('id', '=', $post->id)->first();
    // dd($myPost->toArray());
    return view('posts.show', ['post' => $myPost]);
  }

  public function edit(Post $post) {
    return view('posts.edit', ['post' => $post]);
  }

  public function update(Request $request, Post $post) {
    $request->validate([
      'title' => 'required|string',
      'content' => 'required|string',
      'image' => 'mimes:jpeg,png,jpg,gif,svg',
      'image.*' => 'mimes:jpeg,png,jpg,gif,svg',
    ]);
    $userId = Auth::user()->id;
    $userIdPost = $post->user_id;
    if ($userId != $userIdPost) {
      toast('This is not your Post', 'error');
      return redirect('/');
    }
    $datas = $request->all();
    if ($files = $request->file('image')) {
      // Define upload path
      $destinationPath = public_path('/images/'); // upload path
      // Upload Orginal Image
      $profileImage = date('YmdHis') . "." . $files->getClientOriginalExtension();
      $files->move($destinationPath, $profileImage);
      $datas['url_image'] = "$profileImage";
    }
    $post->fill($datas);
    $post->save();
    toast('Post Has Been Updated !', 'success');
    return redirect('/');
  }

  public function destroy(Post $post) {
    $userId = Auth::user()->id;
    $userIdPost = $post->user_id;
    if ($userId != $userIdPost) {
      toast('This is not your Post', 'error');
      return redirect('/');
    }
    toast('Post Has Been Deleted !', 'success');
    $post->delete();
    return redirect('/');
  }

  public function like(Request $request, Post $post) {
    toast('Post Has Been Liked !', 'success');
    $userId = Auth::user()->id;
    $datas = $request->all();
    $datas['user_id'] = $userId;
    $datas['post_id'] = $post->id;
    try {
      PostLike::create($datas);
    } catch (QueryException $e) {
      $errorCode = $e->errorInfo[1];
      if ($errorCode == 1062) {
        toast('Ups !! Already Liked', 'error');
        return redirect()->back();
      }
    }
    toast('Post Has Liked !', 'success');
    return redirect()->back();
  }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-9">
      <div class="card">
        <div class="card-header">
          <span>Create Post</span>
        </div>
        <div class="card-body">
          <form method="POST" action="{{ route('posts.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group row">
              <label for="title" class="col-md-2 col-form-label text-md-right">
                Title Post
              </label>
              <div class="col-md-10">
                <input id="title" type="title" class="form-control @error('title') is-invalid @enderror" name="title" />
                @error('title')
                  <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                  </span>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label for="content" class="col-md-2 col-form-label text-md-right">
                Content Post
              </label>
              <div class="col-md-10">
                <textarea name="content" class="form-control my-editor @error('content') is-invalid @enderror">{!! old('content', $content ?? "") !!}</textarea>
                @error('content')
                  <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                  </span>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label for="image" class="col-md-2 col-form-label text-md-right">
                Image Post
              </label>
              <div class="col-md-10">
                <div class="custom-file">
                  <input type="file" name="image" id="image" onchange="loadPreview(this);" class="custom-file-input  @error('image') is-invalid @enderror">
                  <label class="custom-file-label" for="inputGroupFile01">Choose File</label>
                  @error('image')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
                <img class="mt-3" id="preview_img" src="https://www.w3adda.com/wp-content/uploads/2019/09/No_Image-128.png" class="" width="100" height="100" />
              </div>
            </div>
            <div class="form-group row mb-0">
              <div class="col-md-10 offset-md-2">
                <button type="submit" class="btn btn-primary">
                  Submit
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@include("posts.scripts")
@push("scripts.footer")

@endpush

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-9">
      <div class="card">
        <div class="card-header">Update Posts </div>
        <div class="card-body">
          <form method="POST" action="{{ route('posts.update', ['post' => $post]) }}" enctype="multipart/form-data">
            @csrf
            @method("PATCH")
            <div class="form-group row">
              <label for="title" class="col-md-2 col-form-label text-md-right">
                Title Post
              </label>
              <div class="col-md-10">
                <input id="title" type="title" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ $post->title ?? "" }}" />
                @error('title')
                  <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                  </span>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label for="content" class="col-md-2 col-form-label text-md-right">
                Content Post
              </label>
              <div class="col-md-10">
                <textarea name="content" class="form-control my-editor @error('content') is-invalid @enderror">{!! $post->content ?? "" !!}</textarea>
                @error('content')
                  <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                  </span>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label for="image" class="col-md-2 col-form-label text-md-right">
                Image Post
              </label>
              <div class="col-md-10">
                <div class="custom-file">
                  <input type="file" name="image" id="image" onchange="loadPreview(this);" class="custom-file-input  @error('image') is-invalid @enderror">
                  <label class="custom-file-label" for="inputGroupFile01">Choose File</label>
                  @error('image')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
                @if(!empty($post->url_image))
                  <img class="mt-3" id="preview_img" src="{{ asset("/images/".$post->url_image) }}" class="" width="100" height="100" />
                @else
                  <img class="mt-3" id="preview_img" src="https://www.w3adda.com/wp-content/uploads/2019/09/No_Image-128.png" class="" width="100" height="100" />
                @endif
              </div>
            </div>
            <div class="form-group row mb-0">
              <div class="col-md-10 offset-md-2">
                <button type="submit" class="btn btn-primary">
                  Submit
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@include("posts.scripts")

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <div class="row justify-content-between align-items-center px-3">
            <span>
              @if(empty($isAll))
                My List Posts
              @else
                All Posts From All Users
              @endif
            </span>
            <a href="{{ route('posts.create') }}" class="btn btn-primary">Add Posts</a>
          </div>
        </div>
        <div class="card-body">
          @foreach($posts as $post)
            @include('posts.components.postcard',['post' => $post])
          @endforeach
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/posts/scripts.blade.php
@push("scripts.footer")
  <script>
    var editor_config = {
      path_absolute: "/",
      selector: "textarea.my-editor",
      plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern"
      ],
      toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
      relative_urls: false,
      file_browser_callback: function(field_name, url, type, win) {
        var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
        var y = window.innerHeight || document.documentElement.clientHeight || document.getElementsByTagName('body')[0].clientHeight;

        var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
        if (type == 'image') {
          cmsURL = cmsURL + "&type=Images";
        } else {
          cmsURL = cmsURL + "&type=Files";
        }

        tinyMCE.activeEditor.windowManager.open({
          file: cmsURL,
          title: 'Filemanager',
          width: x * 0.8,
          height: y * 0.8,
          resizable: "yes",
          close_previous: "no"
        });
      }
    };

    tinymce.init(editor_config);
  </script>
  <script>
    function loadPreview(input, id) {
      id = id || '#preview_img';
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function(e) {
          $(id)
            .attr('src', e.target.result)
            .width(200)
            .height(150);
        };

        reader.readAsDataURL(input.files[0]);
      }
    }
  </script>
@endpush

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <div class="row justify-content-between align-items-center px-3">
            <span>Post Detail </span>
          </div>
        </div>
        <div class="card-body">
          @include('posts.components.postcard',['post' => $post,'isShow' => true])
          <p class="text-title-comment">List Comments</p>
          @foreach($post->comments as $comment)
            <div class="posts-comment">
              <p>{{ $comment->user->name }}'s Says : </p>
              {!! $comment->content !!}
              <div class="row px-3 justify-content-between align-items-end">
                <div>
                  <?php 
                  $isAlreadyLike = false;
                  ?>
                  @foreach($comment->likes as $like)
                    @if(Auth::user()->id == $like->user_id)
                      <?php
                      $isAlreadyLike = true;
                      ?>
                    @endif
                  @endforeach

                  @if($isAlreadyLike)
                    <span class="mr-1">
                      Already Liked
                    </span>
                  @else
                    <form method="POST" action="{{ route('comments.like', ['comment' => $comment]) }}" style="display: inline">
                      @csrf
                      <input type="submit" value="Like" class="btn btn-link py-0 px-0 pr-2" />
                    </form>
                  @endif
                  <span>({{ $comment->likes_count ?? "0" }} Likes)</span>
                  <span class="mx-1"> - </span>
                  <span class="text-black-50">Commented on : {{ $comment->created_at->diffForHumans() }}</span>
                </div>
                @if(Auth::user()->id == $comment->user_id)
                  <form action="{{ route('comments.delete', ['comment' => $comment]) }}" method="post">
                    <input class="text-danger p-0 m-0 btn btn-sm btn-link" type="submit" value="Delete" />
                    @csrf
                    @method("DELETE")
                  </form>
                @endif
              </div>
            </div>
          @endforeach
          <div class="mt-4">
            <form method="POST" action="{{ route('comments.store',['post'=>$post]) }}" enctype="multipart/form-data">
              @csrf
              <div class="form-group row">
                <div class="col-md-12">
                  <textarea name="content" class="form-control my-editor @error('content') is-invalid @enderror">{!! old('content', $content ?? "") !!}</textarea>
                  @error('content')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                  @enderror
                </div>
              </div>
              <div class="form-group row mb-0">
                <div class="col-md-12 ">
                  <button type="submit" class="btn btn-secondary px-4">
                    Comment
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@include("posts.scripts")